### PR TITLE
remove setasign/fpdi-fpdf because it is abandonned

### PR DESCRIPTION
**Pull request by it-can**

### CODE REVIEW

**Comment by it-can** [comment]
@jurosh can you merge this and release a new version? composer is complaining...

**Comment by spajxo** [comment]
@jurosh friendly bump :)

**Comment by jurosh** [comment]
Eh thanks, will try to release it :) wasn't doing that in a while..

**Comment by PazkaL** [comment]
Hello @jurosh could you also tag a new release please?

**Comment by jurosh** [comment]
@PazkaL Oups, thanks. Updated

**Pull request merged**
